<script>
export default {
	setup() {
		const snmpLocation = '1234 Street St. Boise, ID 83704';
		const hostName = 'HOSTNAME';
		const sygMgmtIp = '10.50.2.21';
		const custMgmtIp = '10.255.32.21';
		const sygDefaultRoute = '10.50.2.20';
		const custDefaultRoute = '10.255.32.20';

		return {
			snmpLocation,
			hostName,
			sygMgmtIp,
			custMgmtIp,
			sygDefaultRoute,
			custDefaultRoute
		};
	}
};
</script>

<template>
	<div>
		<h3 :class="$style.h3">Palo Alto Configuration</h3>
		<div :class="$style.inputFlex">
			<div>
				<h6 :class="$style.h6">SNMP Location</h6>
				<input :class="$style.input" v-model="snmpLocation" />
			</div>
			<div>
				<h6 :class="$style.h6">Hostname</h6>
				<input :class="$style.input" v-model="hostName" />
			</div>
			<div>
				<h6 :class="$style.h6">SYG MGMT IP</h6>
				<input :class="$style.input" v-model="sygMgmtIp" />
			</div>
			<div>
				<h6 :class="$style.h6">CUST MGMT IP</h6>
				<input :class="$style.input" v-model="custMgmtIp" />
			</div>
			<div>
				<h6 :class="$style.h6">SYG DEFAULT ROUTE</h6>
				<input :class="$style.input" v-model="sygDefaultRoute" />
			</div>
			<div>
				<h6 :class="$style.h6">CUST DEFAULT ROUTE</h6>
				<input :class="$style.input" v-model="custDefaultRoute" />
			</div>
		</div>
		<pre>
      <code>
  &lt;?xml version="1.0"?&gt;
  &lt;config version="9.0.4" urldb="paloaltonetworks"&gt;
    &lt;devices&gt;
      &lt;entry name="localhost.localdomain"&gt;
        &lt;deviceconfig&gt;
          &lt;setting&gt;
            &lt;custom-logo/&gt;
            &lt;config&gt;
              &lt;rematch&gt;yes&lt;/rematch&gt;
            &lt;/config&gt;
            &lt;management&gt;
              &lt;hostname-type-in-syslog&gt;FQDN&lt;/hostname-type-in-syslog&gt;
            &lt;/management&gt;
          &lt;/setting&gt;
          &lt;system&gt;
            &lt;domain&gt;syringanetworks.net&lt;/domain&gt;
            &lt;snmp-setting&gt;
              &lt;access-setting&gt;
                &lt;version&gt;
                  &lt;v2c&gt;
                    &lt;snmp-community-string&gt;OcmeQTo2&lt;/snmp-community-string&gt;
                  &lt;/v2c&gt;
                &lt;/version&gt;
              &lt;/access-setting&gt;
              &lt;snmp-system&gt;
                &lt;location&gt;<span>{{ snmpLocation }}</span>&lt;/location&gt;
                &lt;contact&gt;Syringa Networks&lt;/contact&gt;
                &lt;send-event-specific-traps&gt;yes&lt;/send-event-specific-traps&gt;
              &lt;/snmp-system&gt;
            &lt;/snmp-setting&gt;
            &lt;update-server&gt;updates.paloaltonetworks.com&lt;/update-server&gt;
            &lt;dns-setting&gt;
              &lt;servers&gt;
                &lt;primary&gt;192.168.91.5&lt;/primary&gt;
                &lt;secondary&gt;192.168.91.6&lt;/secondary&gt;
              &lt;/servers&gt;
            &lt;/dns-setting&gt;
            &lt;ntp-servers&gt;
              &lt;primary-ntp-server&gt;
                &lt;ntp-server-address&gt;10.16.8.251&lt;/ntp-server-address&gt;
                &lt;authentication-type&gt;
                  &lt;none/&gt;
                &lt;/authentication-type&gt;
              &lt;/primary-ntp-server&gt;
            &lt;/ntp-servers&gt;
            &lt;login-banner&gt;You are logging into a secure system. Any and all activity will be logged.&lt;/login-banner&gt;
            &lt;update-schedule&gt;
              &lt;threats&gt;
                &lt;recurring&gt;
                  &lt;hourly&gt;
                    &lt;action&gt;download-and-install&lt;/action&gt;
                  &lt;/hourly&gt;
                  &lt;threshold&gt;5&lt;/threshold&gt;
                &lt;/recurring&gt;
              &lt;/threats&gt;
              &lt;anti-virus&gt;
                &lt;recurring&gt;
                  &lt;hourly&gt;
                    &lt;action&gt;download-and-install&lt;/action&gt;
                  &lt;/hourly&gt;
                &lt;/recurring&gt;
              &lt;/anti-virus&gt;
            &lt;/update-schedule&gt;
            &lt;timezone&gt;US/Mountain&lt;/timezone&gt;
            &lt;service&gt;
              &lt;disable-telnet&gt;yes&lt;/disable-telnet&gt;
              &lt;disable-http&gt;yes&lt;/disable-http&gt;
            &lt;/service&gt;
            &lt;hostname&gt;<span>{{ hostName }}</span>&lt;/hostname&gt;
            &lt;type&gt;
              &lt;dhcp-client&gt;
                &lt;send-hostname&gt;yes&lt;/send-hostname&gt;
                &lt;send-client-id&gt;yes&lt;/send-client-id&gt;
                &lt;accept-dhcp-hostname&gt;no&lt;/accept-dhcp-hostname&gt;
                &lt;accept-dhcp-domain&gt;no&lt;/accept-dhcp-domain&gt;
              &lt;/dhcp-client&gt;
            &lt;/type&gt;
            &lt;ip-address&gt;192.168.1.1&lt;/ip-address&gt;
            &lt;netmask&gt;255.255.255.252&lt;/netmask&gt;
            &lt;default-gateway&gt;192.168.1.2&lt;/default-gateway&gt;
            &lt;route&gt;
              &lt;service&gt;
                &lt;entry name="deployments"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="dns"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="http"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="ldap"&gt;
                  &lt;source&gt;
                    &lt;address&gt;CUST_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.136&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="mfa"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="ntp"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="paloalto-networks-services"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="panorama"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="radius"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="snmp"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="syslog"&gt;
                  &lt;source&gt;
                    &lt;address&gt;CUST_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.136&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="url-updates"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
                &lt;entry name="wildfire-private"&gt;
                  &lt;source&gt;
                    &lt;address&gt;SYG_MGMT_IP&lt;/address&gt;
                    &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                  &lt;/source&gt;
                &lt;/entry&gt;
              &lt;/service&gt;
            &lt;/route&gt;
            &lt;authentication-profile&gt;RADIUS_AUTH&lt;/authentication-profile&gt;
          &lt;/system&gt;
        &lt;/deviceconfig&gt;
        &lt;vsys&gt;
          &lt;entry name="vsys1" dg-ctxt="40|23"&gt;
            &lt;application/&gt;
            &lt;application-group&gt;
              &lt;entry name="APP_GROUP_SYG"&gt;
                &lt;members&gt;
                  &lt;member&gt;ssl&lt;/member&gt;
                  &lt;member&gt;ssh&lt;/member&gt;
                  &lt;member&gt;icmp&lt;/member&gt;
                  &lt;member&gt;paloalto-updates&lt;/member&gt;
                  &lt;member&gt;dns&lt;/member&gt;
                  &lt;member&gt;panorama&lt;/member&gt;
                  &lt;member&gt;radius&lt;/member&gt;
                  &lt;member&gt;ping&lt;/member&gt;
                  &lt;member&gt;snmp&lt;/member&gt;
                  &lt;member&gt;snmp-trap&lt;/member&gt;
                  &lt;member&gt;ntp&lt;/member&gt;
                  &lt;member&gt;pan-db-cloud&lt;/member&gt;
                  &lt;member&gt;paloalto-wildfire-cloud&lt;/member&gt;
                &lt;/members&gt;
              &lt;/entry&gt;
              &lt;entry name="APP_GROUP_SIMPLOT"&gt;
                &lt;members&gt;
                  &lt;member&gt;ssl&lt;/member&gt;
                  &lt;member&gt;ssh&lt;/member&gt;
                  &lt;member&gt;icmp&lt;/member&gt;
                  &lt;member&gt;syslog&lt;/member&gt;
                  &lt;member&gt;ping&lt;/member&gt;
                &lt;/members&gt;
              &lt;/entry&gt;
            &lt;/application-group&gt;
            &lt;zone&gt;
              &lt;entry name="trust"&gt;
                &lt;network&gt;
                  &lt;virtual-wire&gt;
                    &lt;member&gt;ethernet1/2&lt;/member&gt;
                  &lt;/virtual-wire&gt;
                &lt;/network&gt;
              &lt;/entry&gt;
              &lt;entry name="untrust"&gt;
                &lt;network&gt;
                  &lt;virtual-wire&gt;
                    &lt;member&gt;ethernet1/1&lt;/member&gt;
                  &lt;/virtual-wire&gt;
                &lt;/network&gt;
              &lt;/entry&gt;
              &lt;entry name="SYG_MGMT_ZONE"&gt;
                &lt;network&gt;
                  &lt;layer3&gt;
                    &lt;member&gt;ethernet1/8.99&lt;/member&gt;
                  &lt;/layer3&gt;
                &lt;/network&gt;
              &lt;/entry&gt;
              &lt;entry name="SIMPLOT_MGMT_ZONE"&gt;
                &lt;network&gt;
                  &lt;layer3&gt;
                    &lt;member&gt;ethernet1/8.136&lt;/member&gt;
                  &lt;/layer3&gt;
                &lt;/network&gt;
              &lt;/entry&gt;
            &lt;/zone&gt;
            &lt;service/&gt;
            &lt;service-group/&gt;
            &lt;schedule/&gt;
            &lt;rulebase&gt;
              &lt;security&gt;
                &lt;rules&gt;
                  &lt;entry name="ALLOW_PRIVATE"&gt;
                    &lt;profile-setting&gt;
                      &lt;group&gt;
                        &lt;member&gt;ALLOW_PRIVATE_SPG&lt;/member&gt;
                      &lt;/group&gt;
                    &lt;/profile-setting&gt;
                    &lt;to&gt;
                      &lt;member&gt;trust&lt;/member&gt;
                    &lt;/to&gt;
                    &lt;from&gt;
                      &lt;member&gt;untrust&lt;/member&gt;
                    &lt;/from&gt;
                    &lt;source&gt;
                      &lt;member&gt;RFC_1918&lt;/member&gt;
                    &lt;/source&gt;
                    &lt;destination&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/destination&gt;
                    &lt;source-user&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source-user&gt;
                    &lt;category&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/category&gt;
                    &lt;application&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/application&gt;
                    &lt;service&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/service&gt;
                    &lt;hip-profiles&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/hip-profiles&gt;
                    &lt;action&gt;allow&lt;/action&gt;
                    &lt;log-start&gt;no&lt;/log-start&gt;
                    &lt;log-setting&gt;LOG_FORWARDER&lt;/log-setting&gt;
                  &lt;/entry&gt;
                  &lt;entry name="TRUST_UNTRUST_RFC1918"&gt;
                    &lt;profile-setting&gt;
                      &lt;group&gt;
                        &lt;member&gt;ALLOW_PRIVATE_SPG&lt;/member&gt;
                      &lt;/group&gt;
                    &lt;/profile-setting&gt;
                    &lt;to&gt;
                      &lt;member&gt;untrust&lt;/member&gt;
                    &lt;/to&gt;
                    &lt;from&gt;
                      &lt;member&gt;trust&lt;/member&gt;
                    &lt;/from&gt;
                    &lt;source&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source&gt;
                    &lt;destination&gt;
                      &lt;member&gt;RFC_1918&lt;/member&gt;
                    &lt;/destination&gt;
                    &lt;source-user&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source-user&gt;
                    &lt;category&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/category&gt;
                    &lt;application&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/application&gt;
                    &lt;service&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/service&gt;
                    &lt;hip-profiles&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/hip-profiles&gt;
                    &lt;action&gt;allow&lt;/action&gt;
                    &lt;log-setting&gt;LOG_FORWARDER&lt;/log-setting&gt;
                  &lt;/entry&gt;
                  &lt;entry name="TRUST_UNTRUST"&gt;
                    &lt;to&gt;
                      &lt;member&gt;untrust&lt;/member&gt;
                    &lt;/to&gt;
                    &lt;from&gt;
                      &lt;member&gt;trust&lt;/member&gt;
                    &lt;/from&gt;
                    &lt;source&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source&gt;
                    &lt;destination&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/destination&gt;
                    &lt;source-user&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source-user&gt;
                    &lt;category&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/category&gt;
                    &lt;application&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/application&gt;
                    &lt;service&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/service&gt;
                    &lt;hip-profiles&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/hip-profiles&gt;
                    &lt;action&gt;allow&lt;/action&gt;
                    &lt;profile-setting&gt;
                      &lt;profiles&gt;
                        &lt;url-filtering&gt;
                          &lt;member&gt;SIMPLOT URL Policy&lt;/member&gt;
                        &lt;/url-filtering&gt;
                        &lt;spyware&gt;
                          &lt;member&gt;default&lt;/member&gt;
                        &lt;/spyware&gt;
                        &lt;vulnerability&gt;
                          &lt;member&gt;default&lt;/member&gt;
                        &lt;/vulnerability&gt;
                      &lt;/profiles&gt;
                    &lt;/profile-setting&gt;
                    &lt;log-setting&gt;LOG_FORWARDER&lt;/log-setting&gt;
                  &lt;/entry&gt;
                  &lt;entry name="MGMT_SIMPLOT"&gt;
                    &lt;to&gt;
                      &lt;member&gt;SIMPLOT_MGMT_ZONE&lt;/member&gt;
                    &lt;/to&gt;
                    &lt;from&gt;
                      &lt;member&gt;SIMPLOT_MGMT_ZONE&lt;/member&gt;
                    &lt;/from&gt;
                    &lt;source&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source&gt;
                    &lt;destination&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/destination&gt;
                    &lt;source-user&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source-user&gt;
                    &lt;category&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/category&gt;
                    &lt;application&gt;
                      &lt;member&gt;APP_GROUP_SIMPLOT&lt;/member&gt;
                    &lt;/application&gt;
                    &lt;service&gt;
                      &lt;member&gt;application-default&lt;/member&gt;
                    &lt;/service&gt;
                    &lt;hip-profiles&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/hip-profiles&gt;
                    &lt;action&gt;allow&lt;/action&gt;
                    &lt;log-setting&gt;LOG_FORWARDER&lt;/log-setting&gt;
                    &lt;rule-type&gt;universal&lt;/rule-type&gt;
                    &lt;negate-destination&gt;no&lt;/negate-destination&gt;
                    &lt;profile-setting&gt;
                      &lt;group&gt;
                        &lt;member&gt;SIMPLOT_DEFAULT_SPG&lt;/member&gt;
                      &lt;/group&gt;
                    &lt;/profile-setting&gt;
                  &lt;/entry&gt;
                  &lt;entry name="MGMT_SYG"&gt;
                    &lt;to&gt;
                      &lt;member&gt;SYG_MGMT_ZONE&lt;/member&gt;
                    &lt;/to&gt;
                    &lt;from&gt;
                      &lt;member&gt;SYG_MGMT_ZONE&lt;/member&gt;
                    &lt;/from&gt;
                    &lt;source&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source&gt;
                    &lt;destination&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/destination&gt;
                    &lt;source-user&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source-user&gt;
                    &lt;category&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/category&gt;
                    &lt;application&gt;
                      &lt;member&gt;APP_GROUP_SYG&lt;/member&gt;
                    &lt;/application&gt;
                    &lt;service&gt;
                      &lt;member&gt;application-default&lt;/member&gt;
                    &lt;/service&gt;
                    &lt;hip-profiles&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/hip-profiles&gt;
                    &lt;action&gt;allow&lt;/action&gt;
                    &lt;rule-type&gt;universal&lt;/rule-type&gt;
                    &lt;negate-destination&gt;no&lt;/negate-destination&gt;
                  &lt;/entry&gt;
                  &lt;entry name="DENY_ANY"&gt;
                    &lt;to&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/to&gt;
                    &lt;from&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/from&gt;
                    &lt;source&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source&gt;
                    &lt;destination&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/destination&gt;
                    &lt;source-user&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/source-user&gt;
                    &lt;category&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/category&gt;
                    &lt;application&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/application&gt;
                    &lt;service&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/service&gt;
                    &lt;hip-profiles&gt;
                      &lt;member&gt;any&lt;/member&gt;
                    &lt;/hip-profiles&gt;
                    &lt;action&gt;deny&lt;/action&gt;
                    &lt;log-setting&gt;LOG_FORWARDER&lt;/log-setting&gt;
                  &lt;/entry&gt;
                &lt;/rules&gt;
              &lt;/security&gt;
              &lt;default-security-rules&gt;
                &lt;rules/&gt;
              &lt;/default-security-rules&gt;
              &lt;application-override&gt;
                &lt;rules/&gt;
              &lt;/application-override&gt;
              &lt;decryption&gt;
                &lt;rules/&gt;
              &lt;/decryption&gt;
              &lt;tunnel-inspect&gt;
                &lt;rules/&gt;
              &lt;/tunnel-inspect&gt;
              &lt;authentication&gt;
                &lt;rules/&gt;
              &lt;/authentication&gt;
              &lt;nat&gt;
                &lt;rules/&gt;
              &lt;/nat&gt;
              &lt;qos&gt;
                &lt;rules/&gt;
              &lt;/qos&gt;
              &lt;pbf&gt;
                &lt;rules/&gt;
              &lt;/pbf&gt;
              &lt;dos&gt;
                &lt;rules/&gt;
              &lt;/dos&gt;
            &lt;/rulebase&gt;
            &lt;import&gt;
              &lt;network&gt;
                &lt;interface&gt;
                  &lt;member&gt;ethernet1/2&lt;/member&gt;
                  &lt;member&gt;loopback&lt;/member&gt;
                  &lt;member&gt;ethernet1/8&lt;/member&gt;
                  &lt;member&gt;ethernet1/8.99&lt;/member&gt;
                  &lt;member&gt;ethernet1/8.136&lt;/member&gt;
                &lt;/interface&gt;
              &lt;/network&gt;
            &lt;/import&gt;
            &lt;address&gt;
              &lt;entry name="SYG_MGMT_IP"&gt;
                &lt;ip-netmask&gt;<span>{{ sygMgmtIp }}</span>&lt;/ip-netmask&gt;
                &lt;description&gt;Management IP in VRF SYG&lt;/description&gt;
              &lt;/entry&gt;
              &lt;entry name="CUST_MGMT_IP"&gt;
                &lt;ip-netmask&gt;<span>{{ custMgmtIp }}</span>&lt;/ip-netmask&gt;
                &lt;description&gt;Management IP in VRF CUST&lt;/description&gt;
              &lt;/entry&gt;
              &lt;entry name="192.168.7.0"&gt;
                &lt;ip-netmask&gt;192.168.7.0/24&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="192.168.64.0"&gt;
                &lt;ip-netmask&gt;192.168.64.0/18&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="10.16.0.0"&gt;
                &lt;ip-netmask&gt;10.16.0.0/15&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="10.45.0.0"&gt;
                &lt;ip-netmask&gt;10.45.0.0/16&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="172.20.4.0"&gt;
                &lt;ip-netmask&gt;172.20.4.0/24&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="172.20.16.0"&gt;
                &lt;ip-netmask&gt;172.20.16.0/24&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="172.20.20.0"&gt;
                &lt;ip-netmask&gt;172.20.20.0/24&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="66.232.64.0"&gt;
                &lt;ip-netmask&gt;66.232.64.0/26&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="66.232.64.64"&gt;
                &lt;ip-netmask&gt;66.232.64.64/27&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="67.215.44.0"&gt;
                &lt;ip-netmask&gt;67.215.44.0/26&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="192.168.0.0"&gt;
                &lt;ip-netmask&gt;192.168.0.0/16&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="10_NET"&gt;
                &lt;ip-netmask&gt;10.0.0.0/8&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="192.168_NET"&gt;
                &lt;ip-netmask&gt;192.168.0.0/16&lt;/ip-netmask&gt;
              &lt;/entry&gt;
              &lt;entry name="172.16_NET"&gt;
                &lt;ip-netmask&gt;172.16.0.0/12&lt;/ip-netmask&gt;
              &lt;/entry&gt;
            &lt;/address&gt;
            &lt;log-settings&gt;
              &lt;profiles&gt;
                &lt;entry name="LOG_FORWARDER"&gt;
                  &lt;match-list&gt;
                    &lt;entry name="AUTH_FORWARDER"&gt;
                      &lt;send-syslog&gt;
                        &lt;member&gt;SYSLOG_SIMPLOT&lt;/member&gt;
                      &lt;/send-syslog&gt;
                      &lt;log-type&gt;auth&lt;/log-type&gt;
                      &lt;filter&gt;All Logs&lt;/filter&gt;
                      &lt;send-to-panorama&gt;no&lt;/send-to-panorama&gt;
                    &lt;/entry&gt;
                    &lt;entry name="TRAFFIC_FORWARDER"&gt;
                      &lt;send-syslog&gt;
                        &lt;member&gt;SYSLOG_SIMPLOT&lt;/member&gt;
                      &lt;/send-syslog&gt;
                      &lt;log-type&gt;traffic&lt;/log-type&gt;
                      &lt;filter&gt;All Logs&lt;/filter&gt;
                      &lt;send-to-panorama&gt;no&lt;/send-to-panorama&gt;
                    &lt;/entry&gt;
                    &lt;entry name="THREAT_FORWARDER"&gt;
                      &lt;send-syslog&gt;
                        &lt;member&gt;SYSLOG_SIMPLOT&lt;/member&gt;
                      &lt;/send-syslog&gt;
                      &lt;log-type&gt;threat&lt;/log-type&gt;
                      &lt;filter&gt;All Logs&lt;/filter&gt;
                      &lt;send-to-panorama&gt;no&lt;/send-to-panorama&gt;
                    &lt;/entry&gt;
                    &lt;entry name="URL_FORWARDER"&gt;
                      &lt;send-syslog&gt;
                        &lt;member&gt;SYSLOG_SIMPLOT&lt;/member&gt;
                      &lt;/send-syslog&gt;
                      &lt;log-type&gt;url&lt;/log-type&gt;
                      &lt;filter&gt;All Logs&lt;/filter&gt;
                      &lt;send-to-panorama&gt;no&lt;/send-to-panorama&gt;
                    &lt;/entry&gt;
                  &lt;/match-list&gt;
                &lt;/entry&gt;
              &lt;/profiles&gt;
            &lt;/log-settings&gt;
            &lt;profiles&gt;
              &lt;url-filtering&gt;
                &lt;entry name="SIMPLOT URL Policy"&gt;
                  &lt;credential-enforcement&gt;
                    &lt;mode&gt;
                      &lt;disabled/&gt;
                    &lt;/mode&gt;
                    &lt;log-severity&gt;medium&lt;/log-severity&gt;
                    &lt;block&gt;
                      &lt;member&gt;abused-drugs&lt;/member&gt;
                      &lt;member&gt;adult&lt;/member&gt;
                      &lt;member&gt;command-and-control&lt;/member&gt;
                      &lt;member&gt;gambling&lt;/member&gt;
                      &lt;member&gt;hacking&lt;/member&gt;
                      &lt;member&gt;malware&lt;/member&gt;
                      &lt;member&gt;nudity&lt;/member&gt;
                      &lt;member&gt;parked&lt;/member&gt;
                      &lt;member&gt;peer-to-peer&lt;/member&gt;
                      &lt;member&gt;phishing&lt;/member&gt;
                      &lt;member&gt;private-ip-addresses&lt;/member&gt;
                      &lt;member&gt;proxy-avoidance-and-anonymizers&lt;/member&gt;
                      &lt;member&gt;questionable&lt;/member&gt;
                    &lt;/block&gt;
                  &lt;/credential-enforcement&gt;
                  &lt;allow-list&gt;
                    &lt;member&gt;zscaler.com&lt;/member&gt;
                    &lt;member&gt;zscaler.net&lt;/member&gt;
                  &lt;/allow-list&gt;
                  &lt;action&gt;block&lt;/action&gt;
                  &lt;block&gt;
                    &lt;member&gt;abused-drugs&lt;/member&gt;
                    &lt;member&gt;adult&lt;/member&gt;
                    &lt;member&gt;command-and-control&lt;/member&gt;
                    &lt;member&gt;gambling&lt;/member&gt;
                    &lt;member&gt;hacking&lt;/member&gt;
                    &lt;member&gt;malware&lt;/member&gt;
                    &lt;member&gt;nudity&lt;/member&gt;
                    &lt;member&gt;parked&lt;/member&gt;
                    &lt;member&gt;peer-to-peer&lt;/member&gt;
                    &lt;member&gt;phishing&lt;/member&gt;
                    &lt;member&gt;private-ip-addresses&lt;/member&gt;
                    &lt;member&gt;proxy-avoidance-and-anonymizers&lt;/member&gt;
                    &lt;member&gt;questionable&lt;/member&gt;
                  &lt;/block&gt;
                &lt;/entry&gt;
              &lt;/url-filtering&gt;
              &lt;virus/&gt;
              &lt;spyware/&gt;
              &lt;vulnerability/&gt;
              &lt;custom-url-category/&gt;
              &lt;file-blocking/&gt;
              &lt;data-filtering/&gt;
              &lt;data-objects/&gt;
              &lt;hip-objects/&gt;
              &lt;hip-profiles/&gt;
              &lt;dos-protection/&gt;
              &lt;decryption/&gt;
              &lt;wildfire-analysis/&gt;
            &lt;/profiles&gt;
            &lt;address-group&gt;
              &lt;entry name="IPV4_MGMT_ACCESS"&gt;
                &lt;static&gt;
                  &lt;member&gt;10.16.0.0&lt;/member&gt;
                  &lt;member&gt;10.45.0.0&lt;/member&gt;
                  &lt;member&gt;66.232.64.0&lt;/member&gt;
                  &lt;member&gt;66.232.64.64&lt;/member&gt;
                  &lt;member&gt;67.215.44.0&lt;/member&gt;
                  &lt;member&gt;172.20.4.0&lt;/member&gt;
                  &lt;member&gt;172.20.16.0&lt;/member&gt;
                  &lt;member&gt;172.20.20.0&lt;/member&gt;
                  &lt;member&gt;192.168.0.0&lt;/member&gt;
                  &lt;member&gt;192.168.7.0&lt;/member&gt;
                  &lt;member&gt;192.168.64.0&lt;/member&gt;
                &lt;/static&gt;
                &lt;description&gt;Management Access IPv4&lt;/description&gt;
              &lt;/entry&gt;
              &lt;entry name="RFC_1918"&gt;
                &lt;static&gt;
                  &lt;member&gt;10_NET&lt;/member&gt;
                  &lt;member&gt;172.16_NET&lt;/member&gt;
                  &lt;member&gt;192.168_NET&lt;/member&gt;
                &lt;/static&gt;
              &lt;/entry&gt;
            &lt;/address-group&gt;
            &lt;external-list/&gt;
            &lt;region/&gt;
            &lt;application-tag/&gt;
            &lt;application-filter/&gt;
            &lt;profile-group&gt;
              &lt;entry name="SIMPLOT_DEFAULT_SPG"&gt;
                &lt;virus&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/virus&gt;
                &lt;spyware&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/spyware&gt;
                &lt;vulnerability&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/vulnerability&gt;
                &lt;url-filtering&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/url-filtering&gt;
                &lt;file-blocking&gt;
                  &lt;member&gt;basic file blocking&lt;/member&gt;
                &lt;/file-blocking&gt;
                &lt;wildfire-analysis&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/wildfire-analysis&gt;
              &lt;/entry&gt;
              &lt;entry name="ALLOW_PRIVATE_SPG"&gt;
                &lt;virus&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/virus&gt;
                &lt;spyware&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/spyware&gt;
                &lt;vulnerability&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/vulnerability&gt;
                &lt;wildfire-analysis&gt;
                  &lt;member&gt;default&lt;/member&gt;
                &lt;/wildfire-analysis&gt;
              &lt;/entry&gt;
            &lt;/profile-group&gt;
            &lt;authentication-object/&gt;
            &lt;tag/&gt;
            &lt;application-status/&gt;
            &lt;threats&gt;
              &lt;vulnerability/&gt;
              &lt;spyware/&gt;
            &lt;/threats&gt;
          &lt;/entry&gt;
        &lt;/vsys&gt;
        &lt;network&gt;
          &lt;interface&gt;
            &lt;ethernet&gt;
              &lt;entry name="ethernet1/1"&gt;
                &lt;virtual-wire&gt;
                  &lt;units/&gt;
                &lt;/virtual-wire&gt;
              &lt;/entry&gt;
              &lt;entry name="ethernet1/2"&gt;
                &lt;virtual-wire&gt;
                  &lt;lldp&gt;
                    &lt;enable&gt;no&lt;/enable&gt;
                  &lt;/lldp&gt;
                  &lt;units/&gt;
                &lt;/virtual-wire&gt;
              &lt;/entry&gt;
              &lt;entry name="ethernet1/8"&gt;
                &lt;layer3&gt;
                  &lt;ipv6&gt;
                    &lt;neighbor-discovery&gt;
                      &lt;router-advertisement&gt;
                        &lt;enable&gt;no&lt;/enable&gt;
                      &lt;/router-advertisement&gt;
                    &lt;/neighbor-discovery&gt;
                  &lt;/ipv6&gt;
                  &lt;ndp-proxy&gt;
                    &lt;enabled&gt;no&lt;/enabled&gt;
                  &lt;/ndp-proxy&gt;
                  &lt;lldp&gt;
                    &lt;enable&gt;no&lt;/enable&gt;
                  &lt;/lldp&gt;
                  &lt;units&gt;
                    &lt;entry name="ethernet1/8.99"&gt;
                      &lt;ipv6&gt;
                        &lt;neighbor-discovery&gt;
                          &lt;router-advertisement&gt;
                            &lt;enable&gt;no&lt;/enable&gt;
                          &lt;/router-advertisement&gt;
                        &lt;/neighbor-discovery&gt;
                      &lt;/ipv6&gt;
                      &lt;ndp-proxy&gt;
                        &lt;enabled&gt;no&lt;/enabled&gt;
                      &lt;/ndp-proxy&gt;
                      &lt;adjust-tcp-mss&gt;
                        &lt;enable&gt;no&lt;/enable&gt;
                      &lt;/adjust-tcp-mss&gt;
                      &lt;ip&gt;
                        &lt;entry name="SYG_MGMT_IP"/&gt;
                      &lt;/ip&gt;
                      &lt;tag&gt;99&lt;/tag&gt;
                      &lt;comment&gt;SYG MGMT&lt;/comment&gt;
                      &lt;interface-management-profile&gt;ALLOW_ICMP_HTTPS&lt;/interface-management-profile&gt;
                    &lt;/entry&gt;
                    &lt;entry name="ethernet1/8.136"&gt;
                      &lt;ipv6&gt;
                        &lt;neighbor-discovery&gt;
                          &lt;router-advertisement&gt;
                            &lt;enable&gt;no&lt;/enable&gt;
                          &lt;/router-advertisement&gt;
                        &lt;/neighbor-discovery&gt;
                      &lt;/ipv6&gt;
                      &lt;ndp-proxy&gt;
                        &lt;enabled&gt;no&lt;/enabled&gt;
                      &lt;/ndp-proxy&gt;
                      &lt;adjust-tcp-mss&gt;
                        &lt;enable&gt;no&lt;/enable&gt;
                      &lt;/adjust-tcp-mss&gt;
                      &lt;ip&gt;
                        &lt;entry name="CUST_MGMT_IP"/&gt;
                      &lt;/ip&gt;
                      &lt;tag&gt;136&lt;/tag&gt;
                      &lt;comment&gt;CUST MGMT&lt;/comment&gt;
                      &lt;interface-management-profile&gt;ALLOW_ICMP_HTTPS&lt;/interface-management-profile&gt;
                    &lt;/entry&gt;
                  &lt;/units&gt;
                &lt;/layer3&gt;
                &lt;comment&gt;MGMT to 1111&lt;/comment&gt;
              &lt;/entry&gt;
            &lt;/ethernet&gt;
            &lt;loopback&gt;
              &lt;adjust-tcp-mss&gt;
                &lt;enable&gt;no&lt;/enable&gt;
              &lt;/adjust-tcp-mss&gt;
            &lt;/loopback&gt;
            &lt;vlan&gt;
              &lt;units/&gt;
            &lt;/vlan&gt;
            &lt;tunnel&gt;
              &lt;units/&gt;
            &lt;/tunnel&gt;
          &lt;/interface&gt;
          &lt;vlan/&gt;
          &lt;virtual-wire&gt;
            &lt;entry name="default-vwire"&gt;
              &lt;interface1&gt;ethernet1/1&lt;/interface1&gt;
              &lt;interface2&gt;ethernet1/2&lt;/interface2&gt;
            &lt;/entry&gt;
          &lt;/virtual-wire&gt;
          &lt;profiles&gt;
            &lt;monitor-profile&gt;
              &lt;entry name="default"&gt;
                &lt;interval&gt;3&lt;/interval&gt;
                &lt;threshold&gt;5&lt;/threshold&gt;
                &lt;action&gt;wait-recover&lt;/action&gt;
              &lt;/entry&gt;
            &lt;/monitor-profile&gt;
            &lt;interface-management-profile&gt;
              &lt;entry name="Allow_Connectivity"&gt;
                &lt;https&gt;yes&lt;/https&gt;
                &lt;ssh&gt;yes&lt;/ssh&gt;
                &lt;ping&gt;yes&lt;/ping&gt;
              &lt;/entry&gt;
              &lt;entry name="ALLOW_ICMP_HTTPS"&gt;
                &lt;http&gt;no&lt;/http&gt;
                &lt;https&gt;yes&lt;/https&gt;
                &lt;ssh&gt;yes&lt;/ssh&gt;
                &lt;ping&gt;yes&lt;/ping&gt;
                &lt;snmp&gt;yes&lt;/snmp&gt;
              &lt;/entry&gt;
            &lt;/interface-management-profile&gt;
          &lt;/profiles&gt;
          &lt;ike&gt;
            &lt;crypto-profiles&gt;
              &lt;ike-crypto-profiles&gt;
                &lt;entry name="default"&gt;
                  &lt;encryption&gt;
                    &lt;member&gt;aes-128-cbc&lt;/member&gt;
                    &lt;member&gt;3des&lt;/member&gt;
                  &lt;/encryption&gt;
                  &lt;hash&gt;
                    &lt;member&gt;sha1&lt;/member&gt;
                  &lt;/hash&gt;
                  &lt;dh-group&gt;
                    &lt;member&gt;group2&lt;/member&gt;
                  &lt;/dh-group&gt;
                  &lt;lifetime&gt;
                    &lt;hours&gt;8&lt;/hours&gt;
                  &lt;/lifetime&gt;
                &lt;/entry&gt;
                &lt;entry name="Suite-B-GCM-128"&gt;
                  &lt;encryption&gt;
                    &lt;member&gt;aes-128-cbc&lt;/member&gt;
                  &lt;/encryption&gt;
                  &lt;hash&gt;
                    &lt;member&gt;sha256&lt;/member&gt;
                  &lt;/hash&gt;
                  &lt;dh-group&gt;
                    &lt;member&gt;group19&lt;/member&gt;
                  &lt;/dh-group&gt;
                  &lt;lifetime&gt;
                    &lt;hours&gt;8&lt;/hours&gt;
                  &lt;/lifetime&gt;
                &lt;/entry&gt;
                &lt;entry name="Suite-B-GCM-256"&gt;
                  &lt;encryption&gt;
                    &lt;member&gt;aes-256-cbc&lt;/member&gt;
                  &lt;/encryption&gt;
                  &lt;hash&gt;
                    &lt;member&gt;sha384&lt;/member&gt;
                  &lt;/hash&gt;
                  &lt;dh-group&gt;
                    &lt;member&gt;group20&lt;/member&gt;
                  &lt;/dh-group&gt;
                  &lt;lifetime&gt;
                    &lt;hours&gt;8&lt;/hours&gt;
                  &lt;/lifetime&gt;
                &lt;/entry&gt;
              &lt;/ike-crypto-profiles&gt;
              &lt;ipsec-crypto-profiles&gt;
                &lt;entry name="default"&gt;
                  &lt;esp&gt;
                    &lt;encryption&gt;
                      &lt;member&gt;aes-128-cbc&lt;/member&gt;
                      &lt;member&gt;3des&lt;/member&gt;
                    &lt;/encryption&gt;
                    &lt;authentication&gt;
                      &lt;member&gt;sha1&lt;/member&gt;
                    &lt;/authentication&gt;
                  &lt;/esp&gt;
                  &lt;dh-group&gt;group2&lt;/dh-group&gt;
                  &lt;lifetime&gt;
                    &lt;hours&gt;1&lt;/hours&gt;
                  &lt;/lifetime&gt;
                &lt;/entry&gt;
                &lt;entry name="Suite-B-GCM-128"&gt;
                  &lt;esp&gt;
                    &lt;encryption&gt;
                      &lt;member&gt;aes-128-gcm&lt;/member&gt;
                    &lt;/encryption&gt;
                    &lt;authentication&gt;
                      &lt;member&gt;none&lt;/member&gt;
                    &lt;/authentication&gt;
                  &lt;/esp&gt;
                  &lt;dh-group&gt;group19&lt;/dh-group&gt;
                  &lt;lifetime&gt;
                    &lt;hours&gt;1&lt;/hours&gt;
                  &lt;/lifetime&gt;
                &lt;/entry&gt;
                &lt;entry name="Suite-B-GCM-256"&gt;
                  &lt;esp&gt;
                    &lt;encryption&gt;
                      &lt;member&gt;aes-256-gcm&lt;/member&gt;
                    &lt;/encryption&gt;
                    &lt;authentication&gt;
                      &lt;member&gt;none&lt;/member&gt;
                    &lt;/authentication&gt;
                  &lt;/esp&gt;
                  &lt;dh-group&gt;group20&lt;/dh-group&gt;
                  &lt;lifetime&gt;
                    &lt;hours&gt;1&lt;/hours&gt;
                  &lt;/lifetime&gt;
                &lt;/entry&gt;
              &lt;/ipsec-crypto-profiles&gt;
              &lt;global-protect-app-crypto-profiles&gt;
                &lt;entry name="default"&gt;
                  &lt;encryption&gt;
                    &lt;member&gt;aes-128-cbc&lt;/member&gt;
                  &lt;/encryption&gt;
                  &lt;authentication&gt;
                    &lt;member&gt;sha1&lt;/member&gt;
                  &lt;/authentication&gt;
                &lt;/entry&gt;
              &lt;/global-protect-app-crypto-profiles&gt;
            &lt;/crypto-profiles&gt;
          &lt;/ike&gt;
          &lt;qos&gt;
            &lt;profile&gt;
              &lt;entry name="default"&gt;
                &lt;class&gt;
                  &lt;entry name="class1"&gt;
                    &lt;priority&gt;real-time&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class2"&gt;
                    &lt;priority&gt;high&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class3"&gt;
                    &lt;priority&gt;high&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class4"&gt;
                    &lt;priority&gt;medium&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class5"&gt;
                    &lt;priority&gt;medium&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class6"&gt;
                    &lt;priority&gt;low&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class7"&gt;
                    &lt;priority&gt;low&lt;/priority&gt;
                  &lt;/entry&gt;
                  &lt;entry name="class8"&gt;
                    &lt;priority&gt;low&lt;/priority&gt;
                  &lt;/entry&gt;
                &lt;/class&gt;
              &lt;/entry&gt;
            &lt;/profile&gt;
          &lt;/qos&gt;
          &lt;virtual-router&gt;
            &lt;entry name="default"&gt;
              &lt;protocol&gt;
                &lt;bgp&gt;
                  &lt;enable&gt;no&lt;/enable&gt;
                  &lt;dampening-profile&gt;
                    &lt;entry name="default"&gt;
                      &lt;cutoff&gt;1.25&lt;/cutoff&gt;
                      &lt;reuse&gt;0.5&lt;/reuse&gt;
                      &lt;max-hold-time&gt;900&lt;/max-hold-time&gt;
                      &lt;decay-half-life-reachable&gt;300&lt;/decay-half-life-reachable&gt;
                      &lt;decay-half-life-unreachable&gt;900&lt;/decay-half-life-unreachable&gt;
                      &lt;enable&gt;yes&lt;/enable&gt;
                    &lt;/entry&gt;
                  &lt;/dampening-profile&gt;
                &lt;/bgp&gt;
              &lt;/protocol&gt;
              &lt;interface/&gt;
            &lt;/entry&gt;
            &lt;entry name="SYG"&gt;
              &lt;ecmp&gt;
                &lt;algorithm&gt;
                  &lt;ip-modulo/&gt;
                &lt;/algorithm&gt;
              &lt;/ecmp&gt;
              &lt;protocol&gt;
                &lt;bgp&gt;
                  &lt;routing-options&gt;
                    &lt;graceful-restart&gt;
                      &lt;enable&gt;yes&lt;/enable&gt;
                    &lt;/graceful-restart&gt;
                  &lt;/routing-options&gt;
                  &lt;enable&gt;no&lt;/enable&gt;
                  &lt;install-route&gt;yes&lt;/install-route&gt;
                &lt;/bgp&gt;
                &lt;rip&gt;
                  &lt;enable&gt;no&lt;/enable&gt;
                &lt;/rip&gt;
                &lt;redist-profile&gt;
                  &lt;entry name="redis_conn"&gt;
                    &lt;filter&gt;
                      &lt;type&gt;
                        &lt;member&gt;connect&lt;/member&gt;
                        &lt;member&gt;static&lt;/member&gt;
                      &lt;/type&gt;
                    &lt;/filter&gt;
                    &lt;priority&gt;1&lt;/priority&gt;
                    &lt;action&gt;
                      &lt;redist/&gt;
                    &lt;/action&gt;
                  &lt;/entry&gt;
                &lt;/redist-profile&gt;
                &lt;ospf&gt;
                  &lt;enable&gt;no&lt;/enable&gt;
                &lt;/ospf&gt;
              &lt;/protocol&gt;
              &lt;interface&gt;
                &lt;member&gt;ethernet1/8.99&lt;/member&gt;
              &lt;/interface&gt;
              &lt;routing-table&gt;
                &lt;ip&gt;
                  &lt;static-route&gt;
                    &lt;entry name="DEFAULT"&gt;
                      &lt;nexthop&gt;
                        &lt;ip-address&gt;<span>{{ sygDefaultRoute }}</span>&lt;/ip-address&gt;
                      &lt;/nexthop&gt;
                      &lt;path-monitor&gt;
                        &lt;enable&gt;no&lt;/enable&gt;
                        &lt;failure-condition&gt;any&lt;/failure-condition&gt;
                        &lt;hold-time&gt;2&lt;/hold-time&gt;
                      &lt;/path-monitor&gt;
                      &lt;interface&gt;ethernet1/8.99&lt;/interface&gt;
                      &lt;metric&gt;10&lt;/metric&gt;
                      &lt;destination&gt;0.0.0.0/0&lt;/destination&gt;
                      &lt;route-table&gt;
                        &lt;unicast/&gt;
                      &lt;/route-table&gt;
                    &lt;/entry&gt;
                  &lt;/static-route&gt;
                &lt;/ip&gt;
              &lt;/routing-table&gt;
            &lt;/entry&gt;
            &lt;entry name="CUST"&gt;
              &lt;ecmp&gt;
                &lt;algorithm&gt;
                  &lt;ip-modulo/&gt;
                &lt;/algorithm&gt;
              &lt;/ecmp&gt;
              &lt;protocol&gt;
                &lt;bgp&gt;
                  &lt;routing-options&gt;
                    &lt;graceful-restart&gt;
                      &lt;enable&gt;yes&lt;/enable&gt;
                    &lt;/graceful-restart&gt;
                  &lt;/routing-options&gt;
                  &lt;enable&gt;no&lt;/enable&gt;
                  &lt;install-route&gt;yes&lt;/install-route&gt;
                &lt;/bgp&gt;
              &lt;/protocol&gt;
              &lt;interface&gt;
                &lt;member&gt;ethernet1/8.136&lt;/member&gt;
              &lt;/interface&gt;
              &lt;routing-table&gt;
                &lt;ip&gt;
                  &lt;static-route&gt;
                    &lt;entry name="DEFAULT"&gt;
                      &lt;path-monitor&gt;
                        &lt;enable&gt;no&lt;/enable&gt;
                        &lt;failure-condition&gt;any&lt;/failure-condition&gt;
                        &lt;hold-time&gt;2&lt;/hold-time&gt;
                      &lt;/path-monitor&gt;
                      &lt;nexthop&gt;
                        &lt;ip-address&gt;<span>{{ custDefaultRoute }}</span>&lt;/ip-address&gt;
                      &lt;/nexthop&gt;
                      &lt;interface&gt;ethernet1/8.136&lt;/interface&gt;
                      &lt;metric&gt;10&lt;/metric&gt;
                      &lt;destination&gt;0.0.0.0/0&lt;/destination&gt;
                      &lt;route-table&gt;
                        &lt;unicast/&gt;
                      &lt;/route-table&gt;
                    &lt;/entry&gt;
                  &lt;/static-route&gt;
                &lt;/ip&gt;
              &lt;/routing-table&gt;
            &lt;/entry&gt;
          &lt;/virtual-router&gt;
        &lt;/network&gt;
      &lt;/entry&gt;
    &lt;/devices&gt;
    &lt;mgt-config&gt;
      &lt;users&gt;
        &lt;entry name="trouble"&gt;
          &lt;permissions&gt;
            &lt;role-based&gt;
              &lt;superuser&gt;yes&lt;/superuser&gt;
            &lt;/role-based&gt;
          &lt;/permissions&gt;
          &lt;phash&gt;$1$tosrsllr$uwQS3IqXxWU/5h.c20nU0.&lt;/phash&gt;
        &lt;/entry&gt;
        &lt;entry name="admin"&gt;
          &lt;phash&gt;$1$qtkmqgqg$vMkszyMCISnL0vA1/1MGk0&lt;/phash&gt;
          &lt;permissions&gt;
            &lt;role-based&gt;
              &lt;superuser&gt;yes&lt;/superuser&gt;
            &lt;/role-based&gt;
          &lt;/permissions&gt;
        &lt;/entry&gt;
        &lt;entry name="simplot"&gt;
          &lt;permissions&gt;
            &lt;role-based&gt;
              &lt;superreader&gt;yes&lt;/superreader&gt;
            &lt;/role-based&gt;
          &lt;/permissions&gt;
          &lt;phash&gt;$1$nqsborgk$8CVMg/NUp.4.Gs7du0C0y0&lt;/phash&gt;
        &lt;/entry&gt;
      &lt;/users&gt;
    &lt;/mgt-config&gt;
    &lt;shared&gt;
      &lt;log-settings&gt;
        &lt;snmptrap&gt;
          &lt;entry name="SNMP_OBSERVIUM"&gt;
            &lt;version&gt;
              &lt;v2c&gt;
                &lt;server&gt;
                  &lt;entry name="OBSERVIUM"&gt;
                    &lt;manager&gt;192.168.80.16&lt;/manager&gt;
                    &lt;community&gt;OcmeQTo2&lt;/community&gt;
                  &lt;/entry&gt;
                &lt;/server&gt;
              &lt;/v2c&gt;
            &lt;/version&gt;
          &lt;/entry&gt;
        &lt;/snmptrap&gt;
        &lt;syslog&gt;
          &lt;entry name="SYSLOG_SIMPLOT"&gt;
            &lt;server&gt;
              &lt;entry name="splunksyslogus.simplot.com"&gt;
                &lt;transport&gt;UDP&lt;/transport&gt;
                &lt;port&gt;514&lt;/port&gt;
                &lt;format&gt;BSD&lt;/format&gt;
                &lt;server&gt;10.10.10.82&lt;/server&gt;
                &lt;facility&gt;LOG_USER&lt;/facility&gt;
              &lt;/entry&gt;
            &lt;/server&gt;
          &lt;/entry&gt;
        &lt;/syslog&gt;
        &lt;system&gt;
          &lt;match-list&gt;
            &lt;entry name="SYSTEM_LOG"&gt;
              &lt;send-syslog&gt;
                &lt;member&gt;SYSLOG_SIMPLOT&lt;/member&gt;
              &lt;/send-syslog&gt;
              &lt;filter&gt;All Logs&lt;/filter&gt;
            &lt;/entry&gt;
          &lt;/match-list&gt;
        &lt;/system&gt;
        &lt;profiles/&gt;
      &lt;/log-settings&gt;
      &lt;content-preview&gt;
        &lt;application/&gt;
        &lt;application-type&gt;
          &lt;category/&gt;
          &lt;technology/&gt;
        &lt;/application-type&gt;
      &lt;/content-preview&gt;
      &lt;application/&gt;
      &lt;application-group/&gt;
      &lt;service/&gt;
      &lt;service-group/&gt;
      &lt;botnet&gt;
        &lt;configuration&gt;
          &lt;http&gt;
            &lt;dynamic-dns&gt;
              &lt;enabled&gt;yes&lt;/enabled&gt;
              &lt;threshold&gt;5&lt;/threshold&gt;
            &lt;/dynamic-dns&gt;
            &lt;malware-sites&gt;
              &lt;enabled&gt;yes&lt;/enabled&gt;
              &lt;threshold&gt;5&lt;/threshold&gt;
            &lt;/malware-sites&gt;
            &lt;recent-domains&gt;
              &lt;enabled&gt;yes&lt;/enabled&gt;
              &lt;threshold&gt;5&lt;/threshold&gt;
            &lt;/recent-domains&gt;
            &lt;ip-domains&gt;
              &lt;enabled&gt;yes&lt;/enabled&gt;
              &lt;threshold&gt;10&lt;/threshold&gt;
            &lt;/ip-domains&gt;
            &lt;executables-from-unknown-sites&gt;
              &lt;enabled&gt;yes&lt;/enabled&gt;
              &lt;threshold&gt;5&lt;/threshold&gt;
            &lt;/executables-from-unknown-sites&gt;
          &lt;/http&gt;
          &lt;other-applications&gt;
            &lt;irc&gt;yes&lt;/irc&gt;
          &lt;/other-applications&gt;
          &lt;unknown-applications&gt;
            &lt;unknown-tcp&gt;
              &lt;destinations-per-hour&gt;10&lt;/destinations-per-hour&gt;
              &lt;sessions-per-hour&gt;10&lt;/sessions-per-hour&gt;
              &lt;session-length&gt;
                &lt;maximum-bytes&gt;100&lt;/maximum-bytes&gt;
                &lt;minimum-bytes&gt;50&lt;/minimum-bytes&gt;
              &lt;/session-length&gt;
            &lt;/unknown-tcp&gt;
            &lt;unknown-udp&gt;
              &lt;destinations-per-hour&gt;10&lt;/destinations-per-hour&gt;
              &lt;sessions-per-hour&gt;10&lt;/sessions-per-hour&gt;
              &lt;session-length&gt;
                &lt;maximum-bytes&gt;100&lt;/maximum-bytes&gt;
                &lt;minimum-bytes&gt;50&lt;/minimum-bytes&gt;
              &lt;/session-length&gt;
            &lt;/unknown-udp&gt;
          &lt;/unknown-applications&gt;
        &lt;/configuration&gt;
        &lt;report&gt;
          &lt;topn&gt;100&lt;/topn&gt;
          &lt;scheduled&gt;yes&lt;/scheduled&gt;
        &lt;/report&gt;
      &lt;/botnet&gt;
      &lt;server-profile&gt;
        &lt;radius&gt;
          &lt;entry name="RADIUS_PROFILE"&gt;
            &lt;protocol&gt;
              &lt;PAP/&gt;
            &lt;/protocol&gt;
            &lt;server&gt;
              &lt;entry name="RADIUS_SERVER"&gt;
                &lt;secret&gt;-AQ==rmrKekjsa9rrr3xQ1t0wAYsAiZ8=e33Q1R13ZADzZtgnDOUEfw==&lt;/secret&gt;
                &lt;port&gt;1645&lt;/port&gt;
                &lt;ip-address&gt;192.168.80.132&lt;/ip-address&gt;
              &lt;/entry&gt;
            &lt;/server&gt;
            &lt;timeout&gt;10&lt;/timeout&gt;
          &lt;/entry&gt;
        &lt;/radius&gt;
      &lt;/server-profile&gt;
      &lt;authentication-profile&gt;
        &lt;entry name="RADIUS_AUTH"&gt;
          &lt;multi-factor-auth&gt;
            &lt;mfa-enable&gt;no&lt;/mfa-enable&gt;
          &lt;/multi-factor-auth&gt;
          &lt;method&gt;
            &lt;radius&gt;
              &lt;server-profile&gt;RADIUS_PROFILE&lt;/server-profile&gt;
              &lt;checkgroup&gt;no&lt;/checkgroup&gt;
            &lt;/radius&gt;
          &lt;/method&gt;
          &lt;allow-list&gt;
            &lt;member&gt;all&lt;/member&gt;
          &lt;/allow-list&gt;
        &lt;/entry&gt;
      &lt;/authentication-profile&gt;
      &lt;authentication-sequence/&gt;
      &lt;admin-role/&gt;
    &lt;/shared&gt;
  &lt;/config&gt;
        </code>
    </pre>
	</div>
</template>

<style lang="stylus" module>
.h3 {
  padding: 4rem;
  margin-top: -3rem;
  color: var(--color-white);
  background-image: var(--gradient-rainbow);
}

.inputFlex {
  display: flex;
  flex-direction: column;
  padding: 3rem 4rem;
  border: 2px solid var(--color-orange-5);
  margin-bottom: 2rem;

  div {
    margin-bottom: 2rem;

    &:last-child {
      margin-bottom: 0;
    }
  }

  .h6 {
    font-family: 'Source Code Pro';
    text-transform: none;
    color: var(--color-orange-5);
    font-weight: 400;
    letter-spacing: 0.25px;
    font-size: 16px;
  }

  input {
    width: 35%;
  }
}

.input {
  color: rgba(0, 0, 0, 0.2);
  background: var(--color-white);
  border: 1px solid var(--color-orange-5);
  padding: 1rem;
  margin-bottom: 1rem;

  &:focus {
    color: rgba(0, 0, 0, 0.8);
    outline: none;
  }
}
</style>
